CREATE TABLE cours (
id INT AUTO_INCREMENT PRIMARY KEY,
nom VARCHAR(100) NOT NULL,
classe_id INT NOT NULL,
credit INT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (classe_id) REFERENCES classes(id) ON DELETE CASCADE
);
CREATE TABLE notes (
id INT AUTO_INCREMENT PRIMARY KEY,
etudiant_id INT NOT NULL,
cours_id INT NOT NULL,
type_note ENUM('CC', 'TP', 'Exam', 'Rattrapage') NOT NULL,
valeur FLOAT NOT NULL,
annee_scolaire VARCHAR(9) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (etudiant_id) REFERENCES etudiants(id) ON DELETE CASCADE,
FOREIGN KEY (cours_id) REFERENCES cours(id) ON DELETE CASCADE
);